config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  root to: 'recipes#index'
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user

  validates :title, :description, presence: true

  has_attached_file :image, styles: { medium: "400x400!>", thumb: "100x100>" }, default_url: "missing.png"
  # validates_with AttachmentPresenceValidator, attributes: :image
  validates_with AttachmentContentTypeValidator, attributes: :image, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :image, less_than: 1.megabytes

  has_many :ingredients, dependent: :destroy
  has_many :directions, dependent: :destroy

  accepts_nested_attributes_for :ingredients,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true
  accepts_nested_attributes_for :directions,
                                reject_if: proc { |attributes| attributes['step'].blank? },
                                allow_destroy: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @recipes = Recipe.all.order('created_at DESC')
  end

  def new
    @recipe = current_user.recipes.build
  end

  def create
    @recipe = current_user.recipes.build(params_recipe)

    if @recipe.save
      flash[:notice] = "Recipe was successfully created"
      redirect_to @recipe
    else
      flash.now[:error] = @recipe.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update(params_recipe)
      flash[:notice] = "Recipe was successfully edited"
      redirect_to @recipe
    else
      flash.now[:error] = @recipe.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:notice] = "Recipe was successfully deleted"
    redirect_to root_path
  end

  private

    def find_recipe
      @recipe = Recipe.find(params[:id])
    end

    def params_recipe
      params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :done, :_destroy], directions_attributes: [:id, :step, :done, :_destroy])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"   # Green
    when "error"
      "alert-danger"    # Red
    when "alert"
      "alert-warning"   # Yellow
    when "notice"
      "alert-info"      # Blue
    else
      flash_type.to_s
    end
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>

  <div class="alert <%= bootstrap_class_for(type) %>">
    <a href="#" data-dismiss="alert" class="close">×</a>

    <% if @recipe.present? && @recipe.errors.any? %>

      <p>
        <%= pluralize(@recipe.errors.count, "error") %> prevented this recipe from saving:
      </p>

      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    <% else %>

      <p>
        <%= message %>
      </p>

    <% end %>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe Vault</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Recipe Vault", root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <!-- <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
           <input type="text" class="form-control" placeholder="Search for recipe">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to current_user.email %></li>
          <% end %>
          <li><%= link_to "New Recipe", new_recipe_path(@recipe) %></li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account<span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
             <li role="separator" class="divider"></li>
             <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
          <% end %>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">

    <%= render partial: "layouts/flash_messages", flash: flash %>

    <%= yield %>
  </div>

</body>
</html>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: "form-input form-control" } %>
    <%= link_to_remove_association "Remove Direction", f, class: "btn btn-danger" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>

  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control form-horizontal' } %>
    <br>
    <%= f.input :description, input_html: { class: 'form-control form-horizontal', rows: "4" } %>
    <br>
    <%= f.file_field :image, as: :file %>
    <br>

    <div class="row">
      <div class="col-md-6">
        <h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-primary add-button" %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <h3>Directions</h3>
        <div id="directions">
          <%= f.simple_fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Direction', f, :directions, class: "btn btn-primary add-button" %>
          </div>
        </div>
      </div>

    </div>

    <%= f.button :submit, class: "btn btn-success" %>
  </div>

<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: "form-input form-control" } %>
    <%= link_to_remove_association "Remove Ingredient", f, class: "btn btn-danger" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render 'form' %>
<br>
<div>
  <%= link_to "Back", @recipe, class: "btn btn-default" %>
</div>

app/views/recipes/index.html.erb
<% @recipes.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-sm-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to image_tag(recipe.image.url(:medium)), recipe %>
          </div>
          <h2><%= link_to recipe.title, recipe %></h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>
<br>
<div>
  <%= link_to "Back", root_path, class: "btn btn-default" %>
</div>

app/views/recipes/show.html.erb
<div class="main_content">
  <div id="recipe_top">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
      </div>
      <div class="col-md-8">
        <div id="recipe_info">
          <h1><%= @recipe.title %></h1>
          <p><%= @recipe.description %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <% @recipe.ingredients.each do |ingredient| %>
          <li><%= ingredient.name %></li>
        <% end %>
      </div>
    </div>

    <div class="col-md-6">
      <div id="directions">
        <h2>Directions</h2>
        <ol>
          <% @recipe.directions.each do |direction| %>
            <li><%= direction.step %></li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>

  <% if user_signed_in? && (@recipe.user == current_user) %>
    <div class="row">
      <div class="col-md-12">
        <%= link_to "Edit Recipe", edit_recipe_path(@recipe), class: "btn btn-success" %>
        <%= link_to "Delete", @recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default add-button" %>
    </div>
  </div>

</div>